<style type="text/css">
<!--
.form{
	background-color: #e88247;
	padding: 40px;
	color: #ffffff;
	text-align: right;	
	/* Set opacity */
	filter: alpha(opacity=95);
	/* IE */
	-moz-opacity: 0.95;
	/* Mozilla */
	opacity: 0.95;
}
#divRegistrationOK{
    background-image: url(<?php echo $this->basePath('img/line-bg.png'); ?>); 
    background-size:100%;
    padding-top: 200px;
	padding-bottom: 200px;	
}
-->
</style>
<div class="row" id="divRegistrationOK">
	<div class="col-md-3 mx-auto">
		<div class="form text-center">
			<h3>REGISTRO</h3>
			<div>&iexcl;Tu registro fue exitoso!</div>
    		<div>Se ha enviado un correo electr&oacute;nico con tu usuario y contrase&ntilde;a</div>
		</div>    	
	</div>	
</div><!-- ./ divRegistrationOK -->